### ISSUE TITLE
Parsing problem

### ISSUE THREAD

**Issue by piotrMocz** [sjrd/scalajsir-calc#4]
Based on the grammar, this is a valid construct:

```
(fun(x) = {x})(5)
```

However, it produces the following parser error:

```
(fun(x) = {x})(5)
    ^
parse error (expected: ")")
```

Is this expected?

**Comment by sjrd** [comment]
Hum that's a bug, indeed.

**Comment by evansb** [comment]
To fix: The `parens` production in `Parser` should be `'(' expr ')'` instead of `'(' addSub ')'`
